### PR TITLE
Possible fix for #505: Sublime Text 3 hangs randomly

### PR DESCRIPTION
**Pull request by w1ndy**
This patch is a workaround for issue #505, which is caused by synchronous pipe operations on the subprocess. The patch includes 2 fixes:

1. Make postCmd method asynchronous by adding a thread and a command queue
2. Enable buffering on subprocess pipe (``bufsize=-1`` uses system settings)

### CODE REVIEW

**Comment by roblav96** [comment]
@w1ndy I spent an entire work day using this patch and can CONFIRM it works flawless! 🌮 🎉 🍰

**Comment by zhengbli** [comment]
Hi @w1ndy thanks for your contribution! Can you sign the CLA so it is safe to check in your code? Thanks!

**Comment by zhengbli** [comment]
LGTM, as soon as the CLA is signed this should be ready to merge. Thanks!

**Comment by w1ndy** [comment]
CLA signed :)

**Comment by zhengbli** [comment]
Hmm, for some reason the CLA bot did not update the status. Did you see the successful notification after you signed ? Sorry for the hassle

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Pull request merged**
