### PR TITLE
Fix #463: Update readme.md to include documentation about typescript_tsdk

### LINKED ISSUE #463: Custom version
I realise that this plugin bundles TypeScript, which sometimes means the version you are compiling your project to differs from the version in this plugin. Is there any way around that, i.e. allowing the user to configure the version? Or, perhaps, the version could be fetched from npm so it's always up to date?

### PR DESCRIPTION
**Pull request by mhegazy**
Fixes https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/458
Fixes https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/463

### CODE REVIEW

**Comment by mhegazy** [comment]
@zhengbli any comments?

**Comment by zhengbli** [comment]
:+1:

**Comment by OliverJAsh** [comment]
Why is this titled “Using a nightly version”? Could it be more generically titled “Using a custom version”?

**Comment by OliverJAsh** [comment]
Thanks for this btw!

**Pull request merged**
