### PR TITLE
Shoud multi-line comments in signature tooltip

### LINKED ISSUE #395: Signature popup doesn't support multiline jsdoc items (only displays first line)
With the below sample, the signature popup only shows the first line of each item. It should merge lines into single string.

```js
/**
   * Line number one, line number one, line number one, line number one, line number one,
   * line 2, does not show up in signature popup.
   *
   * @param {string} prop - Line number one, line number one, line number one.
            Line 2 extra info, does not show up in signature popup.
   */
function(prop: string){
...
}
```

image

### PR DESCRIPTION
**Pull request by zhengbli**
Fix #395 
Edited: added screenshot

capture

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Looks great - can you post a quick screenshot?

**Comment by zhengbli** [comment]
@DanielRosenwasser edited the description.

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by sandersn** [comment]
:+1:

**Pull request merged**
