### PR TITLE
Add option "typescript_auto_format" to turn off auto format + reconfiguring host format settings when they are changed

### PR DESCRIPTION
**Pull request by zhengbli**

### CODE REVIEW

**Comment by steveluc** [comment]
Looks good.  We have typescript_auto_format on the key bindings; do we also need it on the class (I think it won't do any harm either way)?
    {
        "keys": [ ";" ],
        "command": "typescript_format_on_key",
        "args": { "key": ";" },
        "context": [
            { "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true },
            { "key": "setting.typescript_auto_format", "operator": "equal", "operand": true },
            { "key": "selector", "operator": "equal", "operand": "source.ts" }
        ]
    },

**Comment by zhengbli** [comment]
The reason I added this is for now there is no way to disable the auto format if the user doesn't want that (related issue #159)

**Comment by zhengbli** [comment]
Oh now I see what you mean. This is redundant if we already have that in key configs. Closing.

**Comment by zhengbli** [comment]
Reopen because it also contains issue fixes.

**Pull request merged**
