### PR TITLE
Increase error visibility

### PR DESCRIPTION
**Pull request by PSeitz**
Add gutter, outline errors

### CODE REVIEW

**Comment by PSeitz** [comment]
#522 #550 #478

Generally it would be the right thing to extend SublimeLinter 3 (http://www.sublimelinter.com/en/latest/index.html) instead of recreating the SublimeLinter behaviour to get all the nice defaults user expect from Sublime Linting (like disabling #561)

**Comment by betorobson** [comment]
do you have screenshot how it looks like?
You have my vote to aprove this PR!!!

**Comment by betorobson** [comment]
Any update to get erros gutters and output log?
The tooltip mouse over is not helping at all.

**Comment by orta** [comment]
This is deprecated by https://github.com/microsoft/TypeScript-Sublime-Plugin/pull/715

**Pull request closed without merging**
