### PR TITLE
formatted ReadMe with correct path for Typescript sublime plugin installation (for both mac and windows)

### PR DESCRIPTION
**Pull request by mhaviv**

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
While the `.git` is optional, the second command isn't even correct. Thanks for the PR though!

**Comment by mhaviv** [comment]
Hi Daniel sorry about that! I realized there is an extra Typescript written in the second command :// I will pr the correct changes. 
Also I didn’t know that about the .git thank you for the feedback! I’ll add it back also

**Comment by mhaviv** [comment]
Hi @DanielRosenwasser! let me know if all the changes are correct 😊

**Comment by DanielRosenwasser** [comment]
There are no changes according to GitHub, so they look correct. 🙃

**Comment by mhaviv** [comment]
That’s odd... if you look at the commit itself there are changes idk why it states there aren’t changes but I can double check again

**Comment by mhaviv** [comment]
3d3dca97-8d89-4f5e-9545-bd9ba1d41ee2

**Comment by mhaviv** [comment]
Hi @DanielRosenwasser! I double checked that the changes are there. I also added github pull request and github Issue badges to the readme. Let me know if everything looks good 😊

**Comment by orta** [comment]
Hi @mhaviv  - thanks for the PR, I don't think we want to display these on the README. It doesn't really add too much value for people in comparison to putting something infront of the README's actual content - I'm gonna close this PR 

Thanks for trying to help though!

**Pull request closed without merging**
