### PR TITLE
Add support to expand environment variable in node path setting

### PR DESCRIPTION
**Pull request by zhengbli**
related #126

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Does this change only work for `$HOME` as a path variable?

Does this work for `%WINDOWS_STYLE_PATHS%`?

**Comment by billti** [comment]
This is not addressing the customer request exactly, and is not a very flexible design.  Rather than special casing '$HOME', why not just expand any environment variables in the string provided using the API for this that works across platforms, i.e. https://docs.python.org/2/library/os.path.html#os.path.expandvars

**Comment by zhengbli** [comment]
Replaced my own implementation with the python built-in ``os.path.expandvars``, thanks for @billti 's suggestion. Now it supports both mac-style "$VAR" and windows style "%VAR%".

**Comment by mhegazy** [comment]
:+1:

**Pull request merged**
