### PR TITLE
Remove object layer and unify json encode/decode in one place

### PR DESCRIPTION
**Pull request by zhengbli**
Removed the object layer to increase speed.

### CODE REVIEW

**Comment by mhegazy** [comment]
do u have any perf numbers to report before and after the change?

**Comment by zhengbli** [comment]
There is slight perf gain for commands that involve a lot of json-to-object translation, for example the ``format_on_key`` command. I used a unformatted large json file to test the total time between sending out the request and received deserilized response:
```
Before:
2015-04-28 14:44:03,656: 9268: DEBUG: Sending formatonkey request
2015-04-28 14:44:03,656: 9268: DEBUG: Posting command: {"type": "request", "arguments": {"file": "D:\\Users\\zhengbli\\Desktop\\test_json_format.ts", "key": ";", "offset": 3, "line": 3048}, "seq": 7, "command": "formatonkey"}
2015-04-28 14:44:03,781: 3092: DEBUG: Stream state: "init".  Read header: "b'Content-Length: 303218'"
2015-04-28 14:44:03,781: 3092: DEBUG: Stream state: "header".  Read header: "None"
2015-04-28 14:44:03,781: 3092: DEBUG: Read body of length: 303218
2015-04-28 14:44:03,796: 3092: DEBUG: Body sequence#: 7
2015-04-28 14:44:03,796: 3092: DEBUG: Stream state: "init".  Read header: "None"
2015-04-28 14:44:03,796: 9268: DEBUG: Deserilized formatonkey response
Total time: 140 ms

After:
2015-04-28 14:39:41,611: 2572: DEBUG: Sending formatonkey request
2015-04-28 14:39:41,611: 2572: DEBUG: Posting command: {"seq": 7, "type": "request", "arguments": {"offset": 3, "file": "D:\\Users\\zhengbli\\Desktop\\test_json_format.ts", "line": 3048, "key": ";"}, "command": "formatonkey"}
2015-04-28 14:39:41,704: 6952: DEBUG: Stream state: "init".  Read header: "b'Content-Length: 303218'"
2015-04-28 14:39:41,704: 6952: DEBUG: Stream state: "header".  Read header: "None"
2015-04-28 14:39:41,704: 6952: DEBUG: Read body of length: 303218
2015-04-28 14:39:41,704: 6952: DEBUG: Body sequence#: 7
2015-04-28 14:39:41,704: 6952: DEBUG: Stream state: "init".  Read header: "None"
2015-04-28 14:39:41,720: 2572: DEBUG: Deserilized formatonkey response
Total time: 109 ms
```
For file this large the total deserilization time was reduced by 20~30 ms. Although for smaller files the perf gain is not noticeable. 

However the other reasons we want to get rid of the object layer include:
1. Maintenance of the object definition file takes effort but does not yield much gain. This file is currently one of the largest files in our codebase, and has quite complex inheritance hierarchy;
2. Deserilization json into object can potentially be an issue for more complex command in the future, even when it is not obvious now;
3. Without the json-to-object process, it means the only bottle neck we might have is the json deserilization process. As #157 suggests, this can be addressed well with alternative libraries.

**Comment by steveluc** [comment]
Thanks for the performance information.  Great to see the code reduction.  Key reason for this beyond perf and maintenance is that a message may gain fields that are unknown to the client.  This will break the object layer unless **kwargs is passed to every constructor.

**Comment by steveluc** [comment]
:+1:

**Pull request merged**
